{
 "title": "Pulse Docker Logs",
 "description": "Easily view the last x minutes of logs from Pulse Docker containers via Loki data source",
 "tags": [ "pls" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Execution Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"pulse-docker-execution-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Consensus Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{container_name=\"pulse-docker-consensus-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container_name=\"pulse-docker-validator-1\"} |= ``"
    }
   ]
  }
 ]
}